repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
      args:
      - '--args=--disable-rule=aws_db_instance_default_parameter_group'
      - '--args=--disable-rule=terraform_module_pinned_source'
