output "ssh_private_key" {
  description = <<-EOT
    SSH private key which generated by module and its public key 
    part assigned to each of nodes. Don't recommended do this as 
    a private key will be kept open and stored in a state file. 
    Instead of this set variable "ssh_authorized_keys". Please note, 
    if "ssh_authorized_keys" set "ssh_private_key" return empty output
  EOT
  value = (
    local.ssh_authorized_keys ? "" : tls_private_key.core[0].private_key_pem
  )
}

output "alb_dns_name" {
  description = <<-EOT
    ALB external endpoint DNS name. Should use to assign 
    "CNAME" record of public domain
  EOT
  value       = aws_lb.cluster.dns_name
}

output "cluster_url" {
  description = <<-EOT
    Cluster public URL with schema, domain, and port.
    All parameters depend on inputs values and calculated automatically 
    for convenient use. Can be created separately outside a module
  EOT
  value       = local.cluster_url
}

output "nat_public_ips" {
  description = <<-EOT
    NAT public IPs assigned as an external IP for requests from 
    each of the nodes. Convenient to use for restrict application, 
    audit logs, some security groups, or other IP-based security 
    policies. Note: if set "node_allow_public" each node will get 
    its own public IP which will be used for external requests
  EOT
  value       = module.vpc.nat_public_ips
}
